clone:
  depth: full
pipelines:
  branches:
    maint_1.3:
      - step:
          script:
            - git push https://$primeroimstoken@github.com/primeroIMS/primero.git maint_1.3 --tags
    maint_1.4:
      - step:
          script:
            - git push https://$primeroimstoken@github.com/primeroIMS/primero.git maint_1.4 --tags
    maint_1.5:
      - step:
          script:
            - git push https://$primeroimstoken@github.com/primeroIMS/primero.git maint_1.5 --tags
    maint_1.6:
      - step:
          script:
            - git push https://$primeroimstoken@github.com/primeroIMS/primero.git maint_1.6 --tags
    development:
      - step:
          script:
            - git push https://$primeroimstoken@github.com/primeroIMS/primero.git development --tags
    development_v2:
      - step:
          script:
            - git push https://$primeroimstoken@github.com/primeroIMS/primero.git development_v2 --tags
            - git push unicef@vs-ssh.visualstudio.com:v3/unicef/ICTD%20-%20Primero%20X%20DEV/primero development_v2 --tags
