---
version: '3'
services:
  nginx:
    image: 'primero/nginx:${PRIMERO_TAG:-latest}'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot_certs:/certs
      - selfsigned_certs:/etc/certs
      - certbot_var:/var/lib/letsencrypt
      - certbot_etc:/etc/letsencrypt
      - log:/var/log/nginx
      - public:/srv/primero/application/public #TODO:readonly later
      - storage:/srv/primero/application/storage
    env_file:
      - docker/defaults.env
      - docker/local.env
    depends_on:
      - application
  application:
    volumes:
      - storage:/srv/primero/application/storage
    env_file:
      - docker/defaults.env
      - docker/local.env
  solr:
    env_file:
      - docker/defaults.env
      - docker/local.env
  beanstalkd:
    env_file:
      - docker/defaults.env
      - docker/local.env
  backburner:
    volumes:
      - storage:/srv/primero/application/storage
    env_file:
      - docker/defaults.env
      - docker/local.env
  postgres:
    env_file:
      - docker/defaults.env
      - docker/local.env
  scheduler:
    env_file:
      - docker/defaults.env
      - docker/local.env
