version: "2.1"
services:
  app:
    build:
      context: ./dvna
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - mysql-db
    env_file:
      - vars.env

  mysql-db:
    image: mysql:5.7
    expose:
      - "3306"
    env_file:
      - vars.env