dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.1
  - safe-global/safe-contracts@1.3.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.7.1
  - Uniswap/v2-periphery@1.0.0-beta.0
  - Uniswap/v2-core@1.0.1

compiler:
  evm_version: null
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.1'
      - '@gnosis.pm=safe-global/safe-contracts@1.3.0'
      - '@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.7.1/contracts'
      - '@uniswap/v2-periphery=Uniswap/v2-periphery@1.0.0-beta.0'
      - '@uniswap/v2-core=Uniswap/v2-core@1.0.1'

dotenv: .env 

networks:
  default: development
  development:
    max_fee: 1000000001
    priority_fee: 1000000000
