version: "3.7"
services:

  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-pro:7.12.5
    environment:
      - EXTRA_JAVA_OPTIONS="-agentlib:jdwp=transport=dt_socket,address=8882,server=y,suspend=n"
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8882:8882"
    volumes:
      - "./distribution/docker/artifactory:/var/opt/jfrog/artifactory"
