---
AWSTemplateFormatVersion: '2010-09-09'
Description: Provision the Damn Vulnerable Cloud Application's Fargate Backend's ALB

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetAZ0:
    Type: AWS::EC2::Subnet::Id
  SubnetAZ1:
    Type: AWS::EC2::Subnet::Id
  DomainName:
    Type: String
  Certificate:
    Type: String
  HostedZoneId:
    Type: String

Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      Subnets:
      - !Ref SubnetAZ0
      - !Ref SubnetAZ1
      SecurityGroups:
      - !Ref DVCASecurityGroupAlb
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}

  APIDomain:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub fargate-api.${DomainName}
      Type: CNAME
      TTL: '300'
      ResourceRecords:
      - !GetAtt ApplicationLoadBalancer.DNSName

  DVCASecurityGroupAlb:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Allow access to DVCA from anywhere
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 443
        ToPort: 443

  DVCALoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
      - CertificateArn: !Sub arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/${Certificate}
      SslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref DefaultTargetGroup

  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 80
      Protocol: HTTP

Outputs:
  ApplicationLoadBalancer:
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: DVCA-ApplicationLoadBalancer
  ApplicationLoadBalancerSecurityGroup:
    Value: !Ref DVCASecurityGroupAlb
    Export:
      Name: DVCA-ApplicationLoadBalancerSecurityGroup
  ApplicationLoadBalancerDns:
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: DVCA-ApplicationLoadBalancerDns
  ApplicationLoadBalancerListenerArn:
    Value: !Ref DVCALoadBalancerListener
    Export:
      Name: DVCA-DVCALoadBalancerListenerArn
