version: '3'

services:
  db:
    container_name: chaimtube_db_sqli
    build: db/.
    env_file:
      - db/db.env
    networks:
      - sqli
  
  app:
    container_name: chaimtube_app_sqli
    build: app/.
    depends_on:
      - db
    ports:
      - 5001:5000
    networks:
      - sqli

networks:
  sqli: